name: Docker Image CI

on:
  push:
    branches: [ dmckinstry/java-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./apis/user-java
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        
